{{< include ../common/about-this-report.qmd >}}

{{< include ../common/introduction.qmd >}}

### Overview of the Pakistan Data Governance Landscape

**Overview of data governance regime**

**Executive summary**

Data is important for planning and decision-making. Governments around the world collect and maintain data about their citizens and resources to collect taxes and provide civic services. In Pakistan, the government and its entities collect personal data, financial, economic, demographic, and environmental data to include in their decision-making, primarily to create a better living environment for its people.

The Islamic Republic of Pakistan is a federation with a parliamentary form of government. It has a complex legal and governance structure because of the influence of its colonial past, Islamic principles, and modern legal developments. In Pakistan, government entities collect and maintain large repositories of data, including personal data.

This report reviews the laws and policies that establish the data governance regime in the country and explores and critically analyzes the Pakistani data governance landscape. Policies that increase access to data, whether proactively or reactively, are studied in detail. Policies that decrease openness for any reason, such as promoting intellectual property rights, favouring individuals, society, national security, data localization, or protecting privacy, are also examined. There is a deep dive into the positives and negatives of the Personal Data Protection Bill and the Right of Access to Information Act.

The report then discusses its findings about the gaps and frictions in various policies and highlights good practices and potential learnings. There are also findings on the openness of policy development procedures and capacity challenges in the government.

Pakistan's data governance landscape reflects an evolving but fragmented framework. Key priorities include enacting the Personal Data Protection Bill, improving cybersecurity, fostering transparency, and ensuring equitable access to data. Addressing these challenges is critical to achieving digital transformation and protecting citizens' privacy.

**Introduction**

Data has always been important for planning and decision-making, especially for any organization working to serve the masses. Governments around the world collect and maintain data about their citizens and resources to collect taxes and provide civic services. Data is cumbersome to collect on paper at the local level, and difficult to process and compile at the national level, where decisions are made. However, the advancement of information communication technology (ICT) has greatly facilitated data collection, maintenance, and processing for efficient decision-making. For example, it is now possible to sit in a government office in the capital and access multi-layered data from a remote village, compare it with similar villages, identify gaps in comparable services, and create development plans for that village within minutes.

Similarly, businesses collect data to understand customer behaviour, movements, and preferences, enabling them to personalize services or monetize the information through sales to third parties.

As mentioned earlier, the ICT-facilitated ease in data collection has led to the possibility of obtaining large amounts of data on individuals. The corresponding increase in demand for such data has necessitated the redefinition of individuals’ right to privacy vis-a-vis the collection and use of personally identifiable data.

Privacy is a fundamental right enshrined in the Constitution of Pakistan 1973 under Article 14. However, there are currently no data protection or privacy laws in Pakistan. The Ministry of Information Technology and Telecommunication (MoITT) of the Government of Pakistan (GoP) prepared its first draft data protection law in 2005; multiple drafts have followed, but a law is yet to be enacted by the parliament. The current draft is available on the website of MoITT.

Privacy is a fundamental right enshrined in the Constitution of Pakistan 1973 under Article 14[@ConstitutionPK1973]. However, no data protection or privacy laws currently exist in Pakistan. The Ministry of Information Technology and Telecommunication (MoITT)[@moittPK] of the Government of Pakistan (GoP) prepared its first draft data protection law in 2005; multiple drafts have followed, but a law is yet to be enacted by the Parliament. The current draft is available on the MoITT website[@DraftPersonalData2023].

In addition to personal data, government entities also collect financial, economic, demographic, and environmental data to include in their decision-making, primarily to create better living environments for their people.

Before unpacking the data governance regime in Pakistan, it is important to acknowledge the country's particular history and geopolitical situation, both of which have shaped the national mindset and are reflected in national laws and policies. Since its birth in 1947, Pakistan has fought multiple wars, lived through three periods of martial law, lost half of its territory (East Pakistan) in 1971, faced conflicts on its western border in Afghanistan, which also increased religious extremism and terrorism in Pakistan, and suffers a strained relationship with Iran after international sanctions on Iran.

**Legal and governance structure**

**The Constitution:** Pakistan is a federation and has a complex legal and governance structure because of the influence of its colonial past, Islamic principles, and modern legal developments. Pakistan is governed under the Constitution of Pakistan, 1973 (the Constitution). The Constitution, as the supreme law of Pakistan, establishes the country as an Islamic Republic. It provides the framework for the organization of the state, outlining the separation of powers among the executive, legislature, and judiciary.

**Islamic influence:** The most interesting feature of the Constitution is the Objectives Resolution[@ConstitutionPakistan1973, p. 185]. Passed by the Constituent Assembly of Pakistan on March 12, 1949, it laid down the guiding principles for the future Constitution of Pakistan. The Objectives Resolution was later incorporated as a preamble to the 1956, 1962, and the current 1973 Constitutions. Through the Eighth Amendment in 1985, it was made a substantive part of the Constitution of Pakistan; it now serves as the preamble, outlining the Constitution's ideological foundation. Its main objectives are that sovereignty belongs to Allah and that the Islamic way of life shall be observed in Pakistan. The Resolution underscores the importance of Islamic principles in Pakistan's governance and legal framework and aims to blend Islamic values with modern democratic principles.

**Government structure:** The constitution outlines the respective structures and powers of the executive, legislature, and judiciary. The Executive Branch of the State consists of the President, Prime Minister, and the Cabinet. The President is the ceremonial head of state, elected by an electoral college for a term of five years. He has certain powers, including appointing the Prime Minister and other key officials, and can dissolve the National Assembly on the advice of the Prime Minister. The Prime Minister is the head of government, and along with his chosen Ministers in the Cabinet, is responsible for running the federal administration.

Each province has its own government, with a Governor (appointed by the President), a Chief Minister, and a provincial assembly. The provincial assemblies legislate on matters not exclusively reserved for the federal government.

The Legislative Branch consists of Majlis-e-Shoora (Parliament), which is bicameral, consisting of the Senate (upper house) and the National Assembly (lower house). The Senate consists of 96 members, representing the provinces and territories, with equal representation for each province with reserved seats for women, minorities, and technocrats. The election of the Senate is conducted indirectly through respective provincial assemblies, with some seats reserved for women, minorities, and experts. The Senate is a permanent house where all Senators serve six-year terms. Half of the senators are elected every three years. The National Assembly consists of 342 members, directly elected through adult franchise, serving five-year terms. The number of seats for each province is determined by population.

Unlike the Executive and Legislative branches, the Judicial Branch has a single court system. The highest court in the country is the Supreme Court of Pakistan, with the power of judicial review to ensure laws are consistent with the Constitution. Following the twenty-sixth constitutional amendment[@26ConstAmdPK], the Supreme Court will include constitutional benches, which will hear all constitutional matters. There are High Courts in every province and in Islamabad. These courts also have the power of judicial review and original jurisdiction, and also hear appeals against the decisions of the lower courts. The Lower Courts include district courts, session courts, civil and criminal courts.

Because of the Islamic influence, the Constitution has also created a Federal Shariat Court (FSC), with powers to review laws to ensure that they conform to Islamic principles and nullify laws found to be inconsistent with Islamic teachings. The FSC has reviewed and annulled many laws on the touchstone of Islamic principles and directed the government to suitably amend those laws[@LeadingJudgementsFederal2017]. There are also other specialised courts and tribunals created under various laws, including banking courts, accountability courts, tax tribunals, and environmental tribunals.

**Collection and Processing Data:** The major government entities that collect and maintain large repositories of mainly personal data are listed below.

Sector Nature of Data Entity & Data Public sector Personal Data • Pakistan Bureau of Statistics (PBS) • National Database and Registration Authority (NADRA) • Election Commission of Pakistan (ECP) Public Sector Specialized personal data • Federal Board of Revenue (FBR) • National Counter Terrorism Authority (NACTA) • Federal Investigation Agency (FIA) Public Sector Personal data related to registered entities • Securities and Exchange Commission (SECP) • Registrar of Firms • Registrar of Trusts and NGOs • Cooperative Societies Private Regulated Sector Personal data • Telecommunication sector • Banking sector Public Sector Non-personal data • Fiscal Data • Climate Change Data • Public procurement data • Survey of Pakistan • National Archives • Trade and Regional Agreements

**Policies that increase access to data**

**Proactive policies or laws that increase access to data or content**

**Open government data**

The Open Government Partnership (OGP)[@OpenGovPartnershipPK] was launched in 2011 to provide an international platform for domestic reformers committed to making their governments more open, accountable, and responsive to citizens. Pakistan became a member of the OGP in December 2016 during the 4^th^ OGP Summit, joining the ranks of 70 member countries of OGP[@PakistanJoins2016]. At the time of joining, Pakistan reiterated its commitment to the four key principles of OGP: fiscal transparency, access to information, asset disclosures, and citizen engagement. Despite the binding nature of these commitments, Pakistan failed to provide an action plan, resulting in it first being made inactive in 2020[@SCAmendedResolutionPakistanInactivity2020] and ultimately kicked out of the OGP on March 7, 2022[@OGPPakistanLetter2022].

**Open Data Pakistan:** Pakistan's government proactively publishes its policies and basic information on the websites of relevant government entities under the provisions of the RTI. In addition, Open Data Pakistan[@OpenDataPK] is a collaborative effort to help provide open data to all kinds of users by the National Centre for Big Data and Cloud Computing (NCBC), Lahore University of Management Sciences (LUMS), and the Higher Education Commission (HEC).

The Open Data portal is a standardized platform that aims to create a culture of sharing data in Pakistan within every sector. The portal contains over 1,000 datasets[@DatasetsOpenData] across categories such as health, public safety, economy, education, agriculture, demography, connectivity, environment, energy, manufacturing, technology, and culture. These datasets are available in popular open formats such as CSV, XLS(X), PDF, and DOCX.

> However, a review of the portal reveals that most datasets are incomplete or fragmented, making them unreliable. The data is also not updated regularly. Inconsistent formats make it challenging to integrate or analyze the data effectively. For example, there are no available cellular mobile datasets after 2019[@DatasetsOpenData]. The datasets also do not disaggregate voice and data subscribers, which is curious, as the Pakistan Telecommunication Authority regularly publishes such data on its website in much more granular detail. Similarly, rainfall data is available only until December 2016. Smog has recently become a top environmental issue for Lahore: in 2024, the city was declared the world's most polluted city in terms of Air Quality Index (AQI)[@htnewsdeskPakistanAir2024]. Given this, it is striking that the portal provides data only up to April 2020.

**Electronic transactions & records:** The Electronic Transactions Ordinance[@ElectronicTransactionsOrdinancePK2002] (ETO) was promulgated in 2002 to enable the functional equivalence of print and electronic data. ETO addresses all the legal requirements of writing, originality, and retention. It also provides the legal presumptions to electronic data and records, thereby paving the way to legally accept electronic data and transactions, hence increasing access to data.

**Statistical data:** The Pakistan Bureau of Statistics and its statistics collection activities are governed by the following laws:

-   Industrial Statistics Act, 1942[@IndustrialStatisticsAct1942]

-   The General Statistics (Re-organization) Act, 2011[@GeneralStatisticsReorganization2011]

The Population Census Organization was originally established in 1950 as part of the Ministry of Home Affairs. In 1972, it was moved to the Ministry of Interior as an attached department. With the creation of the Registration Organization in 1973, both departments were merged in 1976 and renamed to the "Census & Registration Organization." In March 1978, the Census & Registration Organization was divided into two separate departments. The Population Census Organization was permanently placed under the Statistics Division, which was later renamed as the Pakistan Bureau of Statistics (PBS). The PBS is the principal source of data on Pakistan’s population and economy for public and private sector users, both domestically and internationally. Most of the Pakistan Bureau of Statistics’ data, including recent surveys and the latest population census, is available in PDF on its website. Government departments can access the data free of cost. Non-government entities can access data in other formats for a fee, which locals pay in Pakistani rupees and foreigners pay in US Dollars. The schedule of charges is published on the PBS website. The data thus sold comes with restrictions on further sharing or sale. Supply of sensitive data requires prior approval of the Federal Statistics Authority, i.e., the Secretary, Statistics Division.

The above laws provide the required legal framework for the collection of data, conducting censuses, surveys, and other statistical activities by the PBS in different socioeconomic fields all over the country. These laws also make it binding on the respondents to cooperate with the PBS in furnishing information for statistical purposes.

**All statistics** collected, produced, and published by PBS have two important sources of information: (a) primary data, collected through surveys/censuses, and (b) secondary data collected from administrative records and related sources. Some data is also collected from federal and provincial government departments. Primary sources include statistical data directly collected by PBS through surveys and censuses, while secondary sources include data from various industries and sectors. Data from administrative records includes statistics on public finance and foreign trade. Besides the collection of data on themes like price statistics, industrial statistics, trade statistics, agricultural statistics, labour force and demographic statistics, income and consumption statistics, and social statistics, PBS is also responsible for preparing the national accounts of Pakistan.

> **Gender-disaggregated data:** Gender-disaggregated data is a fundamental tool for achieving gender equality and ensuring that men and women benefit equally from development efforts. It provides the necessary evidence to guide decision-making, policy formulation, and resource allocation, ultimately contributing to a more just and equitable society. PBS foregrounds gender-disaggregated data in the census and other surveys.
>
> PBS conducted its seventh Population and Housing Census in 2023. This was the first ever digital census. The total population is recorded at 241 million, of which 20,331 are transgender people, 124 million are male, and 117 million are female. This puts the gender ratio at 1.06 [@PopulationTables2023]. It is widely believed that the number of female persons is underreported: this is because, in Pakistan's rural and northern areas, men do not want to talk about their female family members. As a result, many women remain unregistered, with no access to civic services, a national ID card, or the right to vote [@GenderSummary2023]. The census report is in PDF format [@CensusKeyFindingsPK2023]. However, it is possible to apply and get census data in other formats for a fee [@DataDisseminationPakistan].
>
> The 2023 census report has basic data like area, population by sex, sex ratio, population density, urban proportion, household size, and annual growth rate. These are available at urban, rural, national, provincial, and district-level scales. The census report also has data on literacy and education, with disaggregation by sex and rural/urban regions. Similarly, data on the economically active population is also divided on the basis of sex and rural-urban segregation. Such gender-disaggregated data is available at all geographical levels, from national to city and village levels, and in all statistics about labour and population welfare. PBS also conducts and publishes demographic surveys that have greater granularity.

> **Data on transgender persons:** The condition of transgender or third-sex people has historically been deplorable in Pakistan, with no enshrined rights to vote or obtain national identity cards, passports, or driving licenses. They were also denied the right to hold or inherit property by their own families. They were typically evicted from their homes with few options besides living with other transgender people. It was also difficult for them to obtain education and employment, forcing them to earn a livelihood by dancing at weddings and through prostitution.

Their condition was first noted by the Supreme Court of Pakistan and in Khaki v. Rawalpindi (2009)[@KhakivRawalpindiSC2009]. The court declared that transgender people are entitled to constitutional rights like any other citizen of Pakistan and directed NADRA to recognize them and the government to grant them fundamental rights. As a result, “transgender” was included as a category for the first time in the 2017 census \[mustafaTransgenderCount2017\].

Finally, 2018 saw the passage of the Transgender Persons (Protection of Rights) Act,[@TransgenderAct2018] which provides adequate protection to this deprived class of individuals. The Act recognises transgender people as equal citizens, provides protection against harassment and protects their right to inherit, right to property, right to education, right to employment, right to vote, and right to hold public office, amongst other fundamental rights. This Act has an overriding effect with respect to any other law and prohibits any discrimination against transgender persons. The most important provision of the law is that a transgender person shall have the right to be recognized as per his or her self-perceived gender identity.

Transgender people continue to face challenges, including being inaccurately counted or recognized. The 2017 general census conducted by the PBS reported the number of transgender people in the country for the first time: it was reported to be 21,774. Later, PBS admitted a "gross undercount" of the trans population. The National AIDS Control Programme under the Federal Health Ministry conducted the Integrated Biological and Behavioral Surveillance (IBBS) survey in 2016-17[@Ibbsround52016] and counted 31,790 transgender persons in only 23 cities [@Ibbsround52016, p. 75]. According to a statement issued by NADRA, the total number of transgender people registered with it stood at 5,626.[@NADRAReg2021] Finally, in the 2023 general census, the transgender population was reported at 20,331,[@PopulationTables2023] which is lower than in the 2017 census. According to transgender rights , despite the 2018 legislation, transgender persons are still not able to access rights, and violence against them continues.[@imranBridgingGap2024] The UNDP reports that, "between 2015 and 2023, over 91 transgender individuals were killed in Khyber Pakhtunkhwa, and more than 2,000 cases of violence against the trans community were reported".[@TransStratFrameworkPK2023]

**National budget and fiscal data:** Articles 78 to 88 of the Constitution are the primary laws governing budget and fiscal data.[@ConstitutionPK1973, p. 56-60]

**National budget and economic survey:** The Finance Division[@FinDivPK] of the Government of Pakistan, in addition to preparing the annual budget[@FinDivBudget2023], also publishes monthly[@MonthlyEconomicUpdates] and annual[@EconomicSurvey2022] economic surveys. The annual data contains an overview of the economy, growth, and investment status, updates on all sectors, inflation, trade and payments, public debt, health and nutrition, population, labour force and employment, social protection, climate change, and economic and social indicators. The Finance Division publishes budget and economic surveys along with statistical data every year in PDF format. The **State Bank of Pakistan** also collects, maintains, and publishes economic data regularly[@statebankofpakistanEasyData].

**Federal Board of Revenue:** The Federal Board of Revenue (FBR) is a government department entrusted with the responsibility of tax collection at the federal level.

The FBR maintains a list of active taxpayers and parliamentarians.[@fbrTaxpayersDirectory] This list is available to the public on the FBR website. The website also provides a free, publicly available service to verify active taxpayers.[@fbrOnlineVerification] Following press reports about most parliamentarians not paying their due share of taxes, the FBR began publishing tax data of parliamentarians along with their constituency.[@slemrodHowTaxpayersRespond] The motivation for publishing data of the rest of the taxpayers was to publicly recognize top taxpayers. It is also believed that such public disclosure may encourage whistleblowers to report disproportionately low tax payments, for example, if they see that a taxpayer's tax payments are too low compared to their income or lifestyle. Both these directories are available online as searchable PDFs and can be downloaded freely. Pakistan has a scheme charging different rates of withholding income tax at source for active taxpayers[@fbrActiveTaxpayer] and non-active taxpayers; this information is therefore vital for all entities that are obliged to withhold tax while making payments.

**Securities data:** The laws that regulate the securities sector are:

-   The Exchange Commission of Pakistan Act, 1997[@ConstitutionPK1973]

-   Stock Exchanges Corporatization, Demutualization and Integration Act 2012[@StockExchanges2012]

-   The Securities Act, 2015[@SecuritiesAct2015]

-   Futures Market Act 2016[@FuturesMarket2016]

**Stock exchange:** SECP regulates the Pakistan Stock Exchange (PSX)[@PakistanStock], the primary stock exchange in Pakistan. PSX was formed in January 2016 following the merger of the Karachi Stock Exchange (KSE), Lahore Stock Exchange (LSE), and Islamabad Stock Exchange (ISE) to create a unified national exchange.

The PSX operates multiple market segments, including the main board, the Small and Medium Enterprises (SME) board, and a market for government securities. It also offers trading in futures, options, and other derivative products. Key indices include the KSE-100 Index, the KSE-30 Index, the KMI-30 Index, and the PSX-KMI All Share Islamic Index.

The PSX also provides a wide range of publicly available information to ensure transparency, facilitate informed investment decisions, and comply with regulatory requirements. In addition to the key indices, it also publishes real-time and historical prices of listed securities, a detailed summary of daily trading activity, including volume, turnover, and number of trades, and market values of listed companies.

Published information regarding listed companies[@GuidanceNotesPSX2023] includes:

-   Basic information, like company name, sector, listing date, and contact details;

-   Quarterly and annual financial reports, including balance sheets, income statements, and cash flow statements;

-   Announcements of dividends, bonus issues, rights issues, stock splits, and mergers or acquisitions;

-   Information on major shareholders and their shareholdings;

-   Details of the board members and key executives;

-   Announcements of significant events or developments affecting a company's business;

-   Quarterly and annual earnings announcements and related presentations; and

-   Filings required by the SECP.

**National Archives:** The National Archives of Pakistan (NAP) are governed under the Archives Material (Preservation and Export Control) Act, 1975[@ArchivalMaterial1975] and The National Archives Act, 1993[@NationalArchivesAct1993]. The National Archives of Pakistan[@NationalArchives] (NAP) is a government-established body to preserve and make available public and private records that have a bearing on the history, culture, and heritage of Pakistan. The NAP is a member of the International Council on Archives[@InternationalCouncil].

Some of the stated functions of NAP are the acquisition, preservation, conservation, reprography, restoration, automation, dissemination, and access of documents. NAP is also responsible for the facilitation of important state documents and collections of dated files. Most of the records are hard copies; some microfilm records exist, and very few records exist in digitised form.

Under Section 8 of the National Archives Act, 1993, public records will be made available 20 years after their creation to the public for reference or research. Records that impact national security are exceptions. Interestingly, while the Act contains an exception to disclosure on national security grounds, no such exception exists for the privacy of individuals.

**Climate change data:** Climate change data is collected and governed by the Global Change Impact Studies Centre Act, 2013[@GlobalChangeAct2013] and The Pakistan Climate Change Act 2017[@PakistanClimateAct2017]. Pakistan is one of the countries worst affected by climate change. According to the Global Climate Risk Index 2021 published by Germanwatch,[@germanwatchGlobalClimate2021] Pakistan is amongst the top ten countries at risk. However, Pakistan is not even present in the Climate Change Performance Index 2023, signalling the extent of efforts made to mitigate the risk.[@burckClimateChange2023]

The Ministry of Climate Change and Environmental Coordination[@MinistryClimate] is the specialized government entity tasked with mainstreaming climate change in economically and socially vulnerable sectors of the economy and steering Pakistan towards climate-resilient development.[@MoCCVisionClimate] The ministry has developed multiple policies in the last 10 years to combat climate change:

-   National Climate Change Policy 2012[@rasulClimateChange2012] (September 03, 2012)

-   National Forest Policy, 2016[@NationalForest2015] (January 27, 2016)

-   National Electric Vehicle Policy, 2019[@NationalElectric2019] (July 19, 2021)

-   National Hazardous Waste Management Policy, 2022[@NationalHazardous2022] (July 25, 2022)

-   Final Updated National Climate Change Policy, 2021[@NationalClimate2021] (March 18, 2022)

-   National Clean Air Policy (NCAP)[@NationalClean2023] (March 02, 2023)

Most of these policy documents are not publicly available on the ministry website. Those policies that are available do not contain adequate data (especially population data) to assess meaningful implementation or policy success/failure. This paucity of data exists despite the Pakistan Meteorological Department[@MetDept] collecting and maintaining data about climate change[@rasulClimateChange2012] and issuing occasional warnings.[@PMDPressReleases] Islamic Relief Canada also conducted a ground survey and published its report "Climate Crisis in Pakistan, Voices from the Ground".[@galloClimateCrisis2023]

**Public procurement data:** The Public Procurement Regulatory Authority (PPRA)[@FederalPublicProc] was created to streamline public procurement and bring transparency to the procurement process. Created through the Public Procurement Regulatory Authority Ordinance, 2002[@PublicProcurement2002] as an autonomous regulatory authority, the PPRA is responsible for preparing regulations and procedures for the federal government and public sector organisations to follow in their procurement processes. It also monitors the procurement undertaken by the public sector.

PPRA provides sector- and organization-wise information on its website about all procurement tenders issued by federal public sector organisations, thus bringing transparency and acting as a one-stop window for all potential suppliers. PPRA also acts as a forum for grievance redressal for bidders[@RedressalGrievances2009].

**Intellectual Property Rights:** By their very nature, laws relating to intellectual property decrease openness and access, with the exception of patents. Under the Patent Ordinance, 2000, a patent is the grant of exclusive rights for 20 years for the inventor to make, use, and sell their invention. To register patents, the investor has to disclose all necessary information. Protection ends once a patent expires: the invention enters the public domain and is available to everyone for commercial exploitation. This system not only increases technological advancement but also increases access to vital information about such advancements.

**National ID System:** After the independence of Pakistan, the first Prime Minister launched the Personal Identity System (PIS) program to register, manage, and issue national identification cards to all the citizens of Pakistan and refugees settling in Pakistan. Changes were carried out by the ECP in 1965 for the process of voters' registration to hold the 1965 presidential election. In 1969- 70, the amendments in the PIS program continued by the ECP until the 1970 general elections.

After the 1971 war and the separation of East Pakistan as Bangladesh, a new statistical database system was needed in what remained of Pakistan (West Pakistan). So the then government introduced the National Registration Act, 1973 to establish an Authority to issue photo IDs to all registered Pakistani citizens [@NationalRegistrationAct1973]. In 1973, in a parliamentary session, the then Prime Minister, emphasising the need for a citizens database, stated that, "due to the absence of a full statistical database of the people of this country, this country is operating in utter darkness"[@maqboolNadrasRole2018]. After the legislation, the government established a database of people and started issuing National Identity Cards (NICs).

The National Database and Registration Authority (NADRA) was established on 10 March 2000 after the promulgation of National Database and Registration Authority Ordinance, 2000[@NationalDatabase2000], by merging Directorate General of Registration, Pakistan, with the National Database Organisation (NDO), an attached department under the Ministry of Interior, created for the 1998 census.

**Identity Cards:** NADRA is an autonomous body to operate independently with the mandate to replace the old NIC with tamper-resistant, ISO-standard Computerised National ID cards (CNIC). NADRA also has the largest repository of biometric information of the people of Pakistan. Every citizen of Pakistan aged 18 and above is eligible to receive the CNIC. The CNIC is mandatory to access any public service, including voting, opening a bank account, buying vehicles and immovable property, a driving license, a passport, a telephone or energy connection, or any other civic service. CNIC is an absolute necessity for meaningful civic life in Pakistan.

**NADRA's** database has proved to be an extremely useful form of digital identification, enabling secure means to deliver financial and Government-to-Person (G2P) services. Because of this database, a lot of transparency has come into the social programmes of the government, like the Social Grant Programme, Financial Inclusion Programmes, Pension Disbursement Program, Border Management and Passport Issuance System, and Disaster Planning and Disaster Recovery Site Development[@SolutionsNADRA2024].

Despite being a government entity established by a federal law, NADRA behaves like a commercial organisation and profits from selling the verification services (Verisys and Biosys) of citizens to private players like banks[@NadraPayment2021] and telecom companies[@burtPakistanTelecom2023] against a very high per-transaction fee[@ranaSIMReverification2015]. After a lot of criticism, NADRA has now started a service to obtain citizen consent before verifying their data to third parties [@correspondentNADRAIntroduces2023]. However, many believe that this service is not working as they did not get any such consent request from NADRA. Security of the data of the citizens with NADRA has been a question mark, as there have been many leaks, including a recent one in which data of 2.7 million citizens has been stolen[@deskNADRAOfficialsDismissed2024]. There have also been reports of biometric data being compromised[@hussainNadraBiometricData2021]. The Digital Rights Foundation reported[@durraniDRFCondemns2018] that several government departments have access to the data. In one instance, NADRA handed over access to citizens' data to the Pakistan IT Board for digitization, which resulted in the data being sold online.

**Data Formats and Interoperability Standards:** Pakistan has adopted many ICT-related policies over the years, including the Pakistan Cloud First Policy, the National Cyber Security Policy, the Digital Pakistan Policy, the Pakistan IT Policy & Action Plan, and the National ICT R&D Fund policy. But it has not established any standard for data format or interoperability of data. No specific format or standard exists: government departments and entities use various formats such as XML, CSV, XLS(X), PDF, and DOCX. The National IT Policy, 2000[@ITPolicy2000] stated an ambition to create standards in section 3.4.14 for ease of sharing data, but to date, no such standards exist. There are standards and formats in various government departments, but not across all government entities.

Back in 2019, an attempt was made to prescribe an open data framework under a "Draft Policy on Open Data for the Government of Pakistan",[@DraftOpenDataPolicyPK2019] but the policy was never approved. The draft policy contained definitions of "Data", "Open data", "Open format", and "Dataset". According to these definitions, the format was to be widely accepted, non-proprietary, platform-independent, and machine-readable, which permits automated processing of such data and facilitates data syntheses and search functionalities.

**Reactive Policies on Allowing Access to Data / Content**

**Right of Access to Information Act:** In line with the Article 19A of the Constitution, the Right of Access to Information Act, 2017[@RightAccess2017] (RTI) was enacted in 2017 to prescribe the process of making requests for information, providing such information by the government entities, and appointing point of contact in every public sector entity. Under the RTI, the Government has also appointed the Pakistan Information Commission (PIC)[@PakistanInformationCommission] to address complaints about denial, refusal/non-provision of requested information, or providing false/incomplete information.

The purpose of the law is to provide the right of access to information transparently and effectively, with few exceptions. Public bodies subject to this law include all ministries, departments, and entities owned or controlled by the federal government, and also include NGOs receiving public funds or registered under any law. All government bodies are required to proactively publish on the web the functions and duties of the body, information about its officials, relevant policies, laws and rules and other necessary information.

Section 7 provides a few exceptions, which include the notes parts of government files, such as opinions, recommendations, and minutes of meetings. Other exceptions include financial institution customer account information, private confidential documents, records relating to defence and national security, and individual privacy. A major exception is that the Minister-in-charge can declare any record not subject to access by simply saying that disclosure is harmful to the public interest (Section 7(f)). So far, no minister has publicly declared any document confidential under the RTI law, however, this power has been criticised by some activists on the ground that it "is vague and evasive and should be removed".[@aliRTILawFixed2023]

**Corporate Data:** The laws that regulate the corporate sector are as follows:

-   The Modarba Companies and Modarba (Floatation Control) Ordinance 1980[@ModarabaCompanies1980]

-   The Exchange Commission of Pakistan Act, 1997[@ConstitutionPK1973]

-   The Companies Act, 2017[@CompaniesAct2017]

-   Insurance Ordinance 2000[@InsuranceOrdinance2000]

-   The Limited Liability Partnership Act, 2020[@LimitedLiability2017]

**Exchange Commission of Pakistan Act:** The Exchange Commission of Pakistan Act 1997 created the Securities and Exchange Commission of Pakistan (SECP)[@SecuritiesExchange2016] as the successor to the Corporate Law Authority (CLA), having an autonomous administrative and financial authority.

Under the Exchange Commission of Pakistan Act, 1997, SECP was initially responsible for the regulation of the corporate sector and capital market. Over time, its mandate has expanded to include supervision and regulation of insurance companies, non-banking finance companies, mutual funds, modarabas (Islamic financing), limited liability partnerships, and private pensions. The SECP has also been entrusted with oversight of various external service providers to the corporate and financial sectors, such as chartered accountants, credit rating agencies, corporate secretaries, brokers, and surveyors.

The regulatory objectives of the SECP are to maintain fair, orderly, and efficient markets, promote robust corporate and insurance sectors, protect the rights of investors, facilitate capital formation, and develop an efficient and dynamic regulatory framework.

**Database of SECP** contains information about all the companies registered with it, including public limited (listed and non-listed), private limited, single-member companies, and limited liability partnerships. It also maintains data about stock and commodity exchanges, depository and clearing institutions, stock and commodity brokerage business, asset management business, investment advisory business, insurance companies, insurance brokerage business, leasing companies, mutual fund distributors, and credit rating companies.

SECP data is not open. Information about directors, shareholders, and promoters of companies incorporated with the SECP is available on application and payment of a fee. However, it is difficult to get information about any Beneficial Owner. From the process of incorporation of new companies, it is visible that SECP asks for information about the Ultimate Beneficial Owner (UBO)[@SECPFrequentlyAsked2020], but it does not appear in the prescribed forms available for inspection online (Form 45[@DeclarationCompliance2020]). Already-registered companies have also been asked to provide information about UBO[@SECPProvides2021].

**Firms, Trusts, NGOs and Coop Societies:** Unlike companies, the regulatory authorities of partnership firms, Trusts, NGOs, and cooperative societies do not publish their data centrally, hence not publicly available. But it is possible to get related information under the RTI from the respective offices of these regulatory authorities.

**Personal Data in Health:** The health sector is governed by the following laws:

-   The Medical Tribunal Act, 2020[@MedicalTribunal2020]

-   The Pakistan Medical and Dental Council Act, 2022[@PakistanMedical2022]

-   The Professional Ethics and Code of Conduct[@PMDCProfessionalEthics]

-   The Pakistan Medical and Dental Council (Postgraduate Education) Regulations, 2023[@PostgraduateMedical2023]

-   The Medical and Dental Undergraduate Education (Admissions, Curriculum and Conduct) Policy and Regulations 2023[@MedicalDental2023]

The health sector is regulated by the Pakistan Medical and Dental Council (PMDC)[@PakistanMedicalDentalCouncil], created under the Pakistan Medical and Dental Council Act, 2022. The PMDC has the power under the Act to prepare and enforce a code of practice and ethics for the medical and dental practitioners, including an obligation to maintain privacy and confidentiality. The code of practice and ethics[@PMDCProfessionalEthics] prepared by PMDC has provisions regarding protecting the patients' privacy and right to confidentiality, unless disclosure of such information is required by law. Unfortunately, patients' privacy is not respected in practice, and the PMDC has failed to enforce this part of the code of practice. If you go to any hospital in Pakistan, you will find that multiple staff members have access to patients' data without any restriction or control. In a study conducted in Lahore, it was concluded that "adherence to principles of ethics in medical practice is inadequate in Pakistan"[@humayunPatientsPerceptionActual2008]. The importance of the privacy and confidentiality of the patients' information is yet to be recognised and enforced through a formal statute to safeguard them[@razaPatientsPrivacy2021]. Hopefully, the situation is likely to be improved after the passing of the draft Data Protection Bill, wherein health data comes within the definition of Sensitive Personal Data[@FinalDraft2023].

**Trade Agreements:** Pakistan has several bilateral trade agreements,[@TradeAgreements2018] under which both parties exchange information. A complete list of such agreements is available online[@PakistanBilateral2021]. One such agreement with Tajikistan on transit trade[@PakistanTajikistan2022] contains provisions regarding data sharing. In this agreement, under Articles 16 and 19, both countries will share data through electronic means. Article 7 of Protocol 4 details provisions regarding the confidentiality of information-sharing and the protection of individual privacy.

**Regional Agreements:** Pakistan is a member of the South Asian Free Trade Area[@SAFTA2004] (SAFTA) and the Asia-Pacific Trade Agreement[@unescapAsiaPacificTrade] (APTA). Pakistan is also a member of the Economic Cooperation Organization[@ecoEconomicCooperation] (ECO) and the Shanghai Cooperation Organisation[@sectSCO] (SCO). However, these are more geared towards trade than data governance.

**MOUs on Statistics:** Pakistan has signed a memorandum of understanding (MOU) on sharing statistical and census data with Sri Lanka[@mouSLPak2016] and Iran[@mouIran2014]. These MOUs pertain to the exchange of statistics on import and export, households, and economic surveys.

**Policies that Decrease Openness**

**Openness**

In Pakistan, certain laws decrease openness or access to information and data. These laws have a wide range, from new laws like the Data Protection Bill to old laws like official secrecy laws.

**Election Commission of Pakistan**: The elections in Pakistan are governed by the following laws, which also grant the Election Commission greater access to voters' personal data:

-   The Constitution of the Islamic Republic of Pakistan 1973 *(Articles 213 to 226)*[@ConstitutionPK1973]

-   The Elections Act, 2017[@ElectionsAct2017]

**Election Act:** The Election Act 2017 recognised the Election Commission of Pakistan (ECP), which was established under previous laws and has been restructured and reformed several times. ECP is an independent, constitutionally established federal body responsible for organising and conducting elections to the Parliament, provincial assemblies, local governments, and the office of President of Pakistan, as well as the delimitation of constituencies and preparation of electoral rolls. It also retains full financial autonomy and independence from all government control.

The functions and duties of ECP are defined and set by the Constitution in Article 219, which assigns the ECP the following duties:

-   To prepare electoral rolls for elections to the National and provincial assemblies and revise such rolls annually;

-   To organise and conduct elections to the Senate and fill casual vacancies in Parliament or a Provincial Assembly;

-   To organise and conduct elections to local government institutions;

-   To appoint election tribunals;

-   To decide cases of disqualification of members of Parliament and provincial assemblies;

-   To hold and conduct the election to the office of the President; and

-   To hold referendums as and when ordered by the President.

ECP maintains a **comprehensive database** of all eligible voters in the country with adequate details to uniquely identify each Voter[@ecpgovdatabase], which increases the visibility of the government into the personal data of its citizens. The information on the electoral rolls contains: name of the voter, his/her parents, permanent and temporary addresses, family number, serial number, statistical block number, and constituency details. ECP also maintains voting stats with following breakups[@ecpgovdatabase]^&^[@ecpvoterinstructions]:

-   Province-wise male and female voters;

-   Age-wise breakup of Voters; and

-   District-wise male and female voters.

The current voters' database is updated as of 30 June 2023[@ecpgovdatabase]. Anyone can verify voting details held by ECP by sending their CNIC number via SMS to 8300 from any mobile network in Pakistan[@ecpCheck].

## Decreasing Openness to Favour Collective rights/ Common good

### Executive Privilege

**Telecom Regulations:** The telecommunication sector is regulated under the Pakistan Telecommunication (Re-organisation) Act 1996[@pakistantelecommunicationauthorityPakistanTelecommunication1996] (Telecom Act). The Telecom Act also establishes the Pakistan Telecommunication Authority (PTA) to act as the regulatory body for the telecommunication sector with adequate powers to issue licenses, ensure compliance, and impose penalties for non-compliance. In the Telecom Act, the federal government has retained some powers, including issuing policy directives, universal service, interception, and rule-making.

Under Section 54 of the Pakistan Telecommunication (Reorganization) Act, 1996 (Telecom Act), the Federal Government has the power to authorise any person to intercept calls and messages violating the privacy of individuals in the national interest or on the mere apprehension of an offence. Under the same section, in case of proclamation of emergency, hostilities or war, the federal government can take over or suspend the operations or services of any telecommunication service provider, thereby depriving their customers of the use of telecommunication services.

The Federal Government has framed the Removal and Blocking of Unlawful Online Content (Procedure, Oversight and Safeguards) Rules, 2021 (the Rules) under the Telecom Act to expand its power to filter or censor information. The civil society in general and the ICT Sector in particular are the worst hit in terms of decreasing access to information. Under Rule 4 of these Rules, PTA has the power of removal or block access to online content in the interest of:

-   Glory of Islam,

-   security of Pakistan,

-   public order,

-   decency and morality, and

-   integrity or defence of Pakistan.

Rule 4 further states that such power of the PTA shall prevail over any contrary community guidelines of the service providers or the social media companies. In addition to this, under Rules 5 and 6, PTA can also exercise this power of removal or blocking of online content on a complaint received from any entity or individual. If the service provider or social media company does not comply, the PTA can downgrade their services or block them in the country.

The Federal Government and PTA have been using these powers quite frequently and even for political reasons. Netblocks has noted in many reports that politically motivated censorship has taken place in the form of blockage or degradation of access to social media[@netblocksInternetDisrupted2023]. PTA went to the extent of restricting Wikipedia in Pakistan over alleged "sacrilegious" content[@netblocksWikipediaRestricted2023]. Micro-blogging site X (formerly Twitter) has been blocked in Pakistan since February 2024[@newsdeskTwitterStill2024].

The government and PTA are in the process of installing and testing China-like 'firewalls' to tighten online surveillance[@hussainPakistanTests2024]. It is feared that the new monitoring system will enable the government to have greater power to monitor the online activities of its citizens. It will enhance the monitoring capabilities on the internet gateways, local data centres, and the internet service providers. According to some internet service providers, the firewall was the reason for growing complaints of poor and slower internet connectivity for the past few months.

The Pakistan Software Houses Association strongly condemned the "hastily implemented national firewall". The Association called the firewall a disaster for the IT sector and also criticised the "prolonged internet disconnections and erratic VPN performance". The disruption was likely to inflict "financial losses estimated to reach \$300 million"[@pakistanitindustryassociationPSHAsOfficial2024].

**Media Regulations:** The Pakistan Electronic Media Regulatory Authority[@PEMRAPakistan] (PEMRA) has been established under the Pakistan Electronic Media Regulatory Authority Ordinance 2002[@PakistanElectronic2002] (the Ordinance) to regulate private electronic media including newspapers, television, and radio. It has the mandate to improve standards of information, education, and entertainment and to enlarge the choice available to the people of Pakistan.

PEMRA occasionally halts broadcasts and closes media outlets under Section 30 of the Ordinance, depriving viewers of necessary access to information. Publication or broadcast of anything objectionable or deemed to be "false or baseless" can bring jail terms of up to three years, and fines of up to 10 million rupees. In the recent past, the majority of cases of suspension of broadcast were politically motivated[@iqbalPEMRASuspends2023].

### 

### National security

**Official Secrets:** The Official Secrets Act 1923[@OfficialSecrets1923] (the Act) without defining, what constitutes a "secret" or "official secret", makes punishable with death, life imprisonment or fourteen years imprisonment a lot of actions, if these are "prejudicial" to public order, defence, safety or interests of the State. The offences include approaching any prohibited place, making any sketch or note useful to an enemy, gaining unauthorised access to documents or information, and disclosing any information related to weapons.

Under Section 3A of the Act, taking photographs or making sketches of any prohibited place, including bridges or any other place notified as such by the government, without written permission, is also an offence punishable by three years' imprisonment. Under Section 5, contrary to the right of freedom of information, any person having any document or information, whether in official capacity or not, communicate it with any unauthorised person or to the enemy or uses it in any manner prejudicial to the safety of the State, will be punishable with fourteen years imprisonment.

The most important case under the Official Secrets Act was filed against the former Prime Minister Imran Khan, commonly known as the cypher case. He was convicted in this case and sentenced to 10 years in jail[@aljazeeraWhatCypher2024]. This case pertained to a diplomatic document sent by the ambassador of Pakistan to the US. Later, in appeal, the conviction was annulled by the higher court[@hussainIslamabadCourt2024]. This case proved that the threat of misuse of the Official Secrets Act is real.

**National Archives:** Though the stated purpose of the National Archives Act, 1993[@NationalArchivesAct1993] (the Act) is to protect and preserve official records, it also gives power to the Director General under Section 7 of the Act, to destroy any public record with the approval of a Committee headed by him, one departmental representative and two nominated academician thereby decreasing access to information and data.

**Survey of Pakistan:** Survey of Pakistan (SoP), established under the Surveying and Mapping Act, 2014[@SurveyingMapping2014], is the national surveying and mapping organization and is the successor of the Royal Survey of India. Its primary responsibility is to conduct all sorts of topographical land surveys of the country and maintain an authentic database of the same.

The main functions of the SoP are to survey and publish topographical maps for general public use and the defence forces of Pakistan. It also establishes and maintains a geodetic network in the entire country. It also conducts surveys on demand.

Though the maps and data of SoP are available for a fee, there are very stringent requirements on their use. Data can neither be shared with third parties nor can it be exported outside of Pakistan, and its commercial use is also prohibited[@UndertakingSoft]. Under the Surveying and Mapping Rules 2015[@ministryofdefenseSurveyingMapping2015] and the Rules for the Publication, Classification, Issue and Custody of Maps, 1981[@ministryofdefenseRulesPublication1981], all maps can be classified as "TOP SECRET, SECRET, RESTRICTED AND PUBLIC".

After the amendment in the Act in 2020[@nationalassemblysecretariatActsOrdinances2020] "no one shall print, display, disseminate, use or circulate incorrect and unofficial versions of maps of Pakistan or any part of Pakistan in hard or digital form". Everyone is obligated to get their maps vetted from the Survey of Pakistan before use in any form, which essentially grants the SoP a monopoly on map-making for Pakistan.

**Open street maps** are not allowed in Pakistan for security reasons. After much effort, Google received permission to only show street-view maps of Pakistani cultural sites, which it started doing in 2012[@attaaGoogleLaunches2015]. The list of selected sites includes historic spots in major cities and can be found here[@googleartsandcultureWondersPakistan]. Later, a local company, TPL Maps[@TPLMaps], launched street-view maps for three cities in Pakistan in 2017 with permission from the Survey of Pakistan[@propkstaffStreetView2017]. The images are for selected spots only. TPL Maps provides GIS as a service on a commercial basis[@tplmapsGISService].

**Terrorism & Anti Money Laundering:** Terrorism and anti-money laundering are regulated under the following laws:

-   The United Nations (Security Council) Act, 1948[@UnitedNations1948]

-   The Anti-Terrorism Act, 1997[@AntiTerrorismAct1997]

-   The National Counter Terrorism Authority Act, 2013[@NationalCounter2013]

-   Anti-Money Laundering and Combating the Financing of Terrorism (AML/CFT) Regulations for Banks & DFIs 2017[@MoneyLaundering2017]

**Counter Terrorism:** The National Counter Terrorism Authority (NACTA)[@NACTANational] was established in 2008 as a unit within the Ministry of Interior. In 2013, NACTA was created as a body corporate with administrative and financial autonomy through the National Counter Terrorism Authority Act, 2013. According to the law, NACTA has the power to collect data and intelligence to counter terrorism and extremism.

**NACTA's database** consists of the following:

-   Proscribed Persons[@nactaScheduleIVProscribedPersons]

-   Proscribed Organisations[@nactaProscribedOrganizations2021]

-   UNSC Sanctions[@UNSCSanctions]

The list of proscribed persons is available online and is searchable with various parameters, whereas the list of proscribed organisations is available in PDF format. Both lists are free to access and are updated regularly. None of the financial institutions is permitted to provide financial services to the individuals and organisations in the above lists of NACTA[@MoneyLaundering2017].

**Federal Investigation Agency**: The Federal Investigation Agency (FIA)[@FederalInvestigationa], established under the Federal Investigation Agency Act, 1974[@FederalInvestigation1974], is a national agency to investigate and fight crimes relating to electronic crimes, border control, terrorism, espionage, federal crimes, smuggling and other special crimes assigned to it by the federal government.

Similar to NACTA, FIA also maintains a list of criminals called **Red Book**[@counterterrorismwingfiaMostWantedHigh2021] and updates it regularly with an adequate description including picture and CNIC. The Red Book is available online for everyone to access free of cost.

**Data Retention & Localization**

The information technology revolution in Pakistan started in the year 2000, when the federal government established an Information Technology and Telecom Division and issued an IT Policy and Action Plan 2000 (IT Policy)[@ITPolicy2000]. The IT Policy mentions providing safeguards for the privacy of individuals and the confidentiality of transactions against all possible misuse, including that by the State, within the legal framework.

To support the IT revolution, Pakistan also deregulated and liberalised its telecom sector through Deregulation Policy for the Telecommunication Sector, 2003[@TelecomDeregulation2003], and Mobile Cellular Policy, 2004[@MobileCellular2004], and encouraged broadband through the Broadband Policy, 2004[@BroadbandPolicy2004]. The licenses issued under those policies were the first document mentioning data localisation. The Broadband Policy also encouraged "Locally Located Content" with the motivation to host websites locally for reducing reliance on international bandwidth.

National Database and Registration Authority Ordinance (NADRA), 2000 was promulgated to create a comprehensive digital database of the citizens of Pakistan, while making the NADRA responsible for ensuring due security, secrecy, and necessary safeguards for protection and confidentiality of citizens' data and information contained in the National Data Warehouse. Though not specifically mentioned in the NADRA Ordinance, the NADRA database resides in Pakistan.

The Telecommunications Policy, 2015, contained provisions regarding international standards of customer service and consumer protection, including measures associated with the protection of consumer data and quality services. The requirement of keeping the telecom customer data within Pakistan remained unchanged.

In 2016, the Prevention of Electronic Crimes Act[@PreventionElectronic2016] (PECA) was enacted, which specifically deals with offences relating to the data located in Pakistan. It also makes violations of the privacy of individuals and the confidentiality of data criminal offences under Sections 20 and 40. Using the rule-making powers granted by PECA, the government made "Removal and Blocking of Unlawful Online Content (Procedure, Oversight and Safeguards) Rules, 2021"[@RemovalBlocking2021], to reinforce its data localisation ambition. Under sub-rule (6) of Rule 7 of Removal and Blocking of Unlawful Online Content (Procedure, Oversight and Safeguards) Rules, 2021, a significant social media company must register with PTA, establish an office in Pakistan, appoint an authorized compliance officer, and a dedicated grievance officer, both based in Pakistan and comply with the user data privacy and data localization requirements.

Despite the threat to block the non-compliant social media companies, very few have registered with the PTA under these Rules[@aminRegistrationSSMCs2022]. The Digital Rights Forum has severely criticised[@dadDRFSocial2022] these rules and called the requirement of local presence "a move towards data localisation", which is against the very "nature of the internet." It further observed that such requirements scare away international social media companies.

In parallel, the PTA also came up with certain regulations to reinforce the data localisation requirements, either in the shape of data retention requirements under Public WiFi-Hotspots Regulations 2018 for a period of one year or controlling data flow under its Cyber Security Strategy for Telecom Sector 2023-2028. For the rest of the telecom sector, the period required for data retention is vague and Regulation 8(3) of the Critical Telecom Data and Infrastructure Security Regulations 2020[@CriticalTelecom2020] (CTDISR). The strategy states that "PTA believes in the free flow of data; however, Critical Telecom Data (CTD), as defined in the PTA's Cyber Security Framework - 2022, needs to reside within the geographical boundaries of Pakistan as per the obligations under CTDISR and operators' licenses". The strategy further states that the "localization would only be limited to Personal Identifiable Information (PII) and CTD". The CTD is defined in CTDISR as personal information of telecom customers held by the telecom licensees. "Similarly, the data localization policy will be aligned with the "Data Protection Bill/Act" and "Cloud Policy", it adds.

Meanwhile, on the policy side, the government reiterated its commitment to data protection law in the Digital Pakistan Policy[@DigitalPakistan2019], Pakistan Vision 2025[@PakistanVision2025], and National Cyber Security Policy 2021[@NationalCyber2021]. The big shift came with the introduction of the Cloud First Policy 2022[@CloudFirst2022], which mentions data residency requirements and the concept of data sovereignty. The Pakistan Cloud First Policy 2022 prescribes that data localization is a rule and transborder data flow is an exception, subject to permission. The Cloud First Policy does acknowledge that cloud hosting is cheaper because of its capabilities and economies of scale, if there is no data residency requirement. The Policy also states that the data belonging to the Government of Pakistan can be stored outside Pakistan if no specific data residency requirements are in place. However, the policy fears that when data is stored outside, it is possible that the government may "lose access to its data" or that the "data may be subject to the laws of other countries" (page 9).

From the benign mention of data localization in the Broadband Policy 2004, it became a mandatory requirement in various frameworks mentioned above. If passed as is, the draft Personal Data Protection (PDP) Bill will finally make it more obvious and applicable across the board. PDP is likely to be used to solidify the data localization requirement and hinder the free flow of data.

The laws and policies mentioned above show a clear and consistent narrative being built around privacy, security, data sovereignty, and consequently, the need for localization. The banking (Enterprise Technology Governance & Risk Management Framework for Financial Institutions, 2017) and telecom (License template) sectors are already obliged to keep the personal data of their customers within Pakistan through mandatory regulations.

It is interesting to note that the PDP allows personal data to be stored outside Pakistan with the consent of the data subject. The data localisation requirement of the banking and telecom sector regulators does not allow that, even with consent, which creates a conflict. It is not clear whether this sector-specific data localization requirement will remain after the enactment of the Personal Data Protection Bill. The PDP, being a general law, would not be able to override the special laws and regulations of the banking and telecom sectors.

The PDP Bill prohibits only the transfer of Critical Personal Data outside Pakistan. However, the fine print empowers the establishment of a Commission under the draft Bill to compel data localization even for personal data and sensitive data. This can be done on the grounds of national security and public interest, even if the data subject has consented to the data being transferred abroad. The draft Bill does not define terms like national security or public interest, raising concerns among stakeholders .

The draft National Artificial Intelligence Policy 2023[@NationalAI2023] claims to be consistent with the Personal Data Protection Bill, Pakistan Cloud First Policy, and the Digital Pakistan Policy initiatives. However, there is a major conflict between this policy and the PDP Bill. The PDP Bill focuses primarily on protecting the privacy and personal data of individuals, whereas AI development depends on access to large amounts of data, including personal data.

**Credit Rating and Defaulters list:** SBP formed the Credit Information Bureau (CIB), which collects and collates credit data on borrowers from its member financial institutions. The financial data is then aggregated in the system, and the resulting information is made available online on request to contributing member financial institutions for credit assessment, credit scoring, and credit risk management. The Electronic Credit Information Bureau (eCIB)[@statebankofpakistanCreditInformation2016] was established by SBP in December 1992 for making CIB data easily accessible to member financial institutions. All Banks, Development Financial Institutions, Non-Bank Financial Companies, and Micro-Finance Banks operating in Pakistan are mandatorily members of the eCIB database and contribute data. Two types of reports are generated from the eCIB system:

-   Consumer Credit Information Report about all individuals and sole proprietors with their CNIC; and

-   Corporate Credit Information Report about Partnership concerns and corporate entities.

Legally, SBP's regulations do not place any restriction on banks and financial institutions on lending to any person/organization, which has an overdue appearing against its account in eCIB or has a late payment/overdue/write-off history. However, in practice, it is unlikely to get a loan after having a bad eCIB. It is possible for an individual to get a credit report from the credit rating agency; however, the process is tedious and discouraging[@datacheckMyCredit]. One has to first register online with the rating agency, then fill out an online form, request credit information, and then the agency will email a PDF of the request form, which the requester has to print, sign, and return with a copy of the CNIC with a fee (currently 100 rupees). After this, the report will be sent in 30 days after verification and approval.

### Decreasing Openness to Favour Individuals

**Justified by Protection of Individual Privacy Rights**

**Data Protection:** Pakistan does not have data protection or privacy laws, despite it being a fundamental right enshrined in Article 14 of the Constitution of Pakistan 1973. The draft Personal Data Protection Bill, 2023[@FinalDraft2023] (the PDP) is in its final shape and is likely to be enacted by the new government, which came into power after the February 2024 elections, after conducting a final round of consultations. Essentially, the law is about protecting the privacy of individuals, but in places, it does restrict and reduce access to information that may otherwise be accessible.

Under Section 16 of the draft PDP, even the data subject's request to access its own data may be declined in the circumstances mentioned in Section 18. These may include: the unavailability of enough information about the data subject or the requester being relevant, inability to locate the requested data, or the requested data cannot be disclosed as it exposes the personal data of someone else, or it may disclose the confidential information relating to the business of the data controller.

Section 30 of the draft PDP restricts the transfer of personal data other than in accordance with the PDP. Section 31 imposes conditions on cross-border transfer. It can only be transferred to a country where an adequate personal data protection legal regime, consistent with PDP, is available and express consent of the data subject is given. However, "Critical Personal Data" cannot be transferred outside Pakistan. In places where an adequate legal regime is not available, Section 32 empowers the Commission to allow transfer of personal data outside Pakistan, if there is a binding contract, there is explicit consent of the data subject, and international cooperation is required.

Disclosure of personal data in violation of PDP is a crime under Section 48 with a fine ranging from United States Dollar (USD) 125,000 to USD 1,000,000, depending on the nature of the personal, sensitive, or critical data.

Pakistan has issued the **Draft National Artificial Intelligence Policy 2023**, which claims to be consistent with the Personal Data Protection Bill, Pakistan Cloud First Policy, and the Digital Pakistan Policy initiatives. However, there is a major conflict between AI policy and the PDP Bill, which has not been resolved in either of the documents. The PDP Bill focuses primarily on protecting the privacy and personal data of individuals, whereas AI development depends on access to large amounts of data.

The PDP does not explicitly mention any exceptions or exemptions for the functioning of search engines; however, there is an exemption in the draft bill for research purposes as long as it does not identify the person or data subject.

The only ground for processing such personal data under Section 6 of the PDP Bill is the consent of the data subject. However, under subsection (6) of Section 6, a data controller may process the personal data of a data subject if the processing is necessary, amongst others, for legitimate interests pursued by the data controller. But the catch is that the term "legitimate interest" in the PDP means anything permitted under the law. So it is safe to assume that the PDP Bill does not recognise web scraping for any purpose, including search engines and machine learning, therefore making it illegal.

**Electronic Crimes:** The Prevention of Electronic Crimes Act, 2016[@PreventionElectronic2016] (PECA) is one of the laws that has been heavily criticised by many, including members of the media industry, because of the offences it creates and the potential for misuse by the government.

From the perspective of decreasing access, the most important provisions are in Sections 11 and 20, which describe "hate speech" and offences against the "dignity" of an individual. As per Section 11, whoever prepares or disseminates information that is likely to advance inter-faith, sectarian or racial hatred shall be punished with imprisonment of up to seven years. Similarly, under Section 20, whoever exhibits or displays or transmits any information to intimidate or harm the reputation or privacy of an individual can be imprisoned for three years. PTA can also remove or block access to such information.

Under Sections 31 and 35 of PECA, the authorised officers have sweeping powers to require any person to provide any data in decrypted form if the authorised officer is satisfied that it is required for an investigation and there is a risk of it being modified, lost, or destroyed. However, he is obliged to bring it to the notice of the court within 24 hours.

Under Section 37 of PECA, PTA has the absolute power to remove or block any information or content in the interest of the glory of Islam or the integrity, security or defence of Pakistan, public order, decency or morality, or in relation to contempt of court or commission of or incitement to an offence. Under Section 48, the Federal Government and PTA have the power to issue directions to any service provider in the interest of the prevention of an offence. Violation of such direction is also made an offence punishable with a fine and imprisonment of up to six months.

PECA has been criticised because of a lack of public awareness, weak prosecution, a lack of information sharing and coordination among the stakeholders, and a lack of proper training of law enforcers, resulting in gross injustice[@iqbalPreventionElectronicCrimes2023a].

Right from the draft to implementation, PECA has been consistently criticised for its potential misuse. And this fear became reality as PECA has been used to arbitrarily target political dissenters, journalists, and human rights activists since its enactment[@WhitePaper2020]. The main target of PECA has been political workers, activists, and journalists. PECA was used to block the website of a political party Awami National Party, and political workers of the Pakistan Muslim League (Nawaz) (PMLN) were targeted before 2022[@ranaBottlenecksIncompetence2018]. After 2022, workers of Pakistan Tehreek-e-Insaf (PTI) are victims[@azizProjectPeca2022], amongst other political parties. This chilling trend also shows the selective misuse of PECA to silence political dissent. According to the co-founder of Bolo Bhi (an advocacy forum for digital rights), "since 2017, journalists critical of state excesses and policies have routinely been targeted using Section 20" of PECA[@azizPecaStrikes2023].

Trialwatch Fairness Report[@trialwatchSection202023], an initiative of Clooney Foundation for Justice, has highlighted the issues with PECA and, in particular, Section 20, which is about defamation. This section has been used to intimidate many journalists, including a famous TV anchor, Imran Riaz Khan.

**In Favour of Promoting Intellectual Property Rights**

**Intellectual Property Rights:** The intellectual property rights in Pakistan are governed by the following laws:

-   The Copyright Ordinance, 1962[@CopyrightOrdinance1962]

-   The Patents Ordinance, 2000[@PatentsOrdinance2000]

-   The Registered Design Ordinance, 2000[@RegisteredDesigns2000]

-   The Registered Layout-Designs of Integrated Circuits Ordinance, 2000[@RegisteredLayout2000]

-   The Trade Marks Ordinance, 2001[@TradeMarks2001]

-   The Geographical Indication (Registration and Protection) Act, 2020[@GeographicalIndications2020]

-   The Intellectual Property Organization of Pakistan Act, 2012[@IntellectualProperty2012]

**Intellectual Property Organization:** In Pakistan, the protection of intellectual property rights (IPRs) is governed by several laws and regulations, having separate entities managing those. Later, the Intellectual Property Organization of Pakistan (IPO) was established as an autonomous body first in 2005, and then it was given legal cover in 2012 by enacting the Intellectual Property Organization of Pakistan Act, 2012, for integrated and efficient intellectual property management. The Trade Marks Registry, Copyright Office, and the Patent and Design Office are now part of the IPO.

Though all the IPR laws provide protection (rather monopoly) to the owners of the IPR for a limited time, these do not prohibit legal use of the protected IPR materials under license or fair use practices.

**AI, Search engines & Web Scraping:** There is no express mention of exempting Artificial Intelligence (AI) and search engines in the IPR laws, including the Copyright Ordinance. The Copyright Ordinance 1962 does not provide any specific exception that covers web scraping for search engines. It also does not explicitly cover scraping of training data for machine learning purposes. However, according to Section 57 of the Copyright Ordinance 1962, a fair dealing with the copyrighted material for research and private study does not constitute an infringement. So, under the assumption that the training of the AI model is for research purposes, it is not an infringement. Similarly, under Section 57, fair dealing with a literary, dramatic, musical or artistic work to report current events in a newspaper, magazine or similar periodical, or the reading or recitation in public of any reasonable extract from a published literary or dramatic work does not constitute an infringement. Therefore, it is assumed that a reasonable amount of copyrighted material displayed by search engines is also not a copyright violation.

**AI Authorship:** The Copyright Ordinance 1962, being an old law, does not recognize work authored or generated by AI, and therefore does not offer protection to it. The Ordinance still classifies "computer program" under the category of "literary work". The Ordinance assumes the "author" to be a natural person, so any works purely generated or authored by AI are not covered by the Ordinance. However, it is debatable whether the natural person commissioning AI (as a tool) to generate original literary, dramatic, musical, or artistic work qualifies to be the author or not, thereby giving copyright protection to the AI-generated work.

**Deep dives into specific aspects**

**Data Protection Bill**

**Data Protection:** Pakistan does not have a comprehensive data protection or privacy law, even though it is a fundamental right enshrined in the Constitution. Pakistan has been working on the data protection law for quite some time, and the first draft of "Electronic Data Protection and Safety Act 2005"[@ElectronicData2005] was published for consultation in 2005. In my article on "Privacy and Islam: From the Quran to Data Protection in Pakistan"[@hayatPrivacyIslam2007], I noted that the main objective of the said draft Pakistani Data Protection Law was to satisfy the requirements of EU Directive 95/46, in particular Article 25 thereof, with the hope of ensuring that data would be allowed to flow freely between the EU and Pakistan, thus making Pakistan an attractive market for outsourcing. After many revisions and feedback of stakeholders, the final draft of the Data Protection Bill[@FinalDraft2023] is available on the website of the MoITT at the time of writing (Nov 2024), and after rounds of consultations it was approved by the Federal Cabinet in July 2023 for submission to the Parliament for enactment[@CabinetApprovesPersonal2023]. Meanwhile, the term of the National Assembly expired, and the bill could not be introduced in the Parliament for enactment.

According to the stated objectives of the draft data protection law, privacy is a fundamental right, and the law lays out the *modus operandi* and ancillary details to protect individuals' data. The law ensures that personal data shall be collected only by lawful, fair, and consensual means from an individual and must be used or disclosed for the purposes for which the data were collected or any other directly related purpose.

The law establishes a Commission called the National Commission for Personal Data Protection of Pakistan (NCPDP) as an autonomous body. Functions of the NCPDP include protecting the interests of the data subject, protecting personal data, precluding misuse of personal data, promoting awareness, and handling complaints of data subjects. The law applies to the data collected and/or processed in Pakistan, irrespective of whether the data controller and data processor are in Pakistan.

According to the draft law, personal data cannot be transferred outside Pakistan unless the country where the data is being transferred offers adequate personal data protection legal regime or in the absence of the legal regime, there is a binding contract in place to protect data and explicit consent of the data subject has been obtained.

It is interesting to note that the right to privacy was granted in the Constitution in 1973. It was only in 2005 that the first draft law on data protection was introduced 2005; it is still not converted to an Act of Parliament, which speaks volumes about the government's seriousness about acknowledging citizens' right to privacy. Back in 2005, the main motivation was to provide a conducive environment for Western countries seeking to outsource business operations to Pakistan. Now, the stated objective is to protect individuals' data and provide extra protection for children.

Babur Suhail, Member Legal of the Ministry of Information Technology and Telecom (MoITT), Government of Pakistan, said that "privacy is a fundamental right under Article 14 of the Constitution and prime motive is guarding the citizens' dignity and privacy and outsourcing business from the western countries was not the main motive". Another Representative of MoITT (henceforth the Representative) explained that "Pakistan is on the road to digitalization and more and more data of citizens are being collected and processed without their knowledge, by all players in the public and private sector, therefore it has become imperative to protect the privacy of citizens". Another motivation was to ensure that companies doing business outside Pakistan are not adversely affected by the absence of this law.

About the delay in enacting the law, the Representative stated that this law had a chance to get approved before the end of the term of the last Government, but the then-Government decided to introduce the E-Safety Bill[@DraftESafety2023] along with this law and, "because of the strong criticism[@CommentsESafetyBill2023] on the E-Safety Bill, both laws stalled".

Both Babur and the Representative of MoITT insisted that the draft law was consistent with GDPR[@NationalArchivesAct1993] and other similar laws in other jurisdictions. However, Mr. Babur admitted that "few other local factors were also kept in mind, like inter-faith matters and security issues" in drafting this law. He also admitted that the category of critical personal data was in addition to the categories of GDPR. The Representative added that the draft law has provided a broad framework; subordinate legislation like Rules and Regulations will be framed later, which shall clear any ambiguity.

Mr. Parvez Iftikhar, an ICT expert, noted that there have been multiple rounds of consultations, to which he also submitted his comments. He also mentioned that the current draft is a lot different from the first draft, which means that some stakeholder feedback had been incorporated.

The representative emphasized that the draft law had the most wide-ranging consultations compared to any law in Pakistan, with broad-based consultation starting in 2020. Over 100 companies and entities, including local and international companies and the European Union, provided feedback. Reflecting on the evolution of the draft, he said that while in the initial draft, cross-border flow of local personal data was not allowed, later data flow was restricted only for critical personal data. However, he admitted that "more personal data can be classified as critical personal data by the NCPDP". The Representative acknowledged that the law will be laid down before the new Parliament, and that since there is some time, "MoITT may try to address some specific concerns of the stakeholders".

There is no doubt that this is an important and much-awaited piece of legislation, and MoITT deserves appreciation for coming up with a good draft. Very wide consultation of the draft for over 3 years is also a commendable sign, which shows the maturity and confidence of the MoITT. They were open to criticism and ready to accept their mistakes and improve the draft legislation to make it acceptable to the majority of the stakeholders, if not all. It appears that in some places, they had to make a compromise to keep the government stakeholders on board.

About the consultation, Mr. Iftikhar said that big internet companies like Meta and Google shared their concerns individually, as well as through the Asia Internet Coalition[@AsiaInternet], their governments, and donor agencies. Some, but not all, comments were addressed in the revised draft. Regarding unaddressed objections on the draft, Mr. Suhail stressed that "every sovereign entity has to watch its interests as sovereignty is an important consideration for every country".

In the absence of Data Protection law, sector regulators like SBP and PTA are regulating the privacy of the customers of their licensees. Their regulations require all personal data to stay in Pakistan. It is unclear whether the personal data held by the licensees of the regulatory bodies would be allowed to be transported outside Pakistan after the passing of the PDP. The MoITT officials hoped that things would change once this draft law was enacted. The Representative added that the PDP will override the practices of the sector regulators as the special law takes precedence over the general law.

Regarding the complaints about NADRA selling data of citizens without their information or consent, the Representative said that "this law was applicable to all public sector organisations and once Rules and Regulations were in place, NADRA would have to follow those".

The draft PDP gives extra protection to the personal data of children under the age of 18 years, whereas in other countries, the age defined for children is much lower. Digital Rights Foundation also sought "clarity on the international business practice of allowing children above the age of 13 to access and use digital services," and it "might create a hindrance for digital platforms to operate in Pakistan"[@DRFLegal2023]. This is likely to create a challenge for internet companies to define a child separately for Pakistan and treat an 18-year-old equal to a 10-year-old.

Bolo Bhi, a civil society organization, expressed its concerns on the draft PDP by saying that the law misses "clauses relating to data processing by government and state institutions"[@bolobhiDataProtection2019]. It also pointed out a potential clash between PDP and PECA over the data retention requirement.

In the definition part of the draft law, there are vague terms like "critical personal data", "legitimate interest", and "public interest", which are likely to be misused to process personal data without the consent of the data subjects. ICT expert Mr. Parvez Iftikhar (henceforth Mr. Iftikhar) observed that "apparently several backdoors have been kept to hinder the free flow of data across borders". He was of the view that the export of critical personal data is restricted, but the term critical personal data is quite vague. He feared that the "government can extend this definition without any restriction".

According to the Digital Rights Foundation, the term critical personal data was "shrouded in ambiguity and had no specifications attached to it[@DRFLegal2023]. The draft Bill relies heavily on the NCPDP to create definitions and provide coherence to the term". It also said that the term public interest was "a complex and tricky concept in general, and the definition of the same under section 2(ff) adds more confusion and vagueness".

In the draft law, exemptions based on vague terms like national security and public interest are bound to be misused by the authorities for political reasons, as is being done for mobile network shutdown and blocking of social media. On the chances of misuse, Mr. Suhail said that "Pakistan has a peculiar situation and its borders are heated all the time, hence security and counter-terrorism are very important considerations".

Interestingly, if data being collected and processed by a public sector entity is similar to that collected and processed by a private sector entity, it would still be treated differently, being critical personal data. For example, data from a customer of a private telecom company and a customer of a public sector company will be treated differently, though there is no difference in the personal data being collected. Indeed, customers might be using both services simultaneously. In addition to the exemptions provided in the PDP, NCPDP is also authorized to give a time-bound exemption to the Federal Government, which is another area of potential misuse.

There are certain offences created by the law, including the unlawful processing of personal data and failure to adopt data security measures. The funny part is that the law prescribes fines in US Dollars (USD) in complete distrust of Pakistan's national currency. The Representative, while explaining the rationale, said that "as the data collected is likely to be sold outside Pakistan in USD, therefore the fine is also proposed to be in USD". On the other hand, Mr. Iftikhar said that because Pakistan is not a strong economy, fluctuation will create a serious challenge in determining the Pakistani Rupee (PKR) equivalence on a given date. "For similar offences, people might be paying widely varying amounts", he feared. It is very unfair to ask people and businesses to pay in USD when they are earning in PKR.

**Right of Access to Information Act**

In line with Article 19A of the Constitution, the Right of Access to Information Act, 2017[@RightAccess2017] was enacted in 2017 to prescribe the process of making requests for information, providing such information by the government entities, and appointing a point of contact in every public sector entity. Pakistan signaled its commitment to the right to information by enshrining it as a fundamental right through a constitutional amendment in 2010. However, when it comes to the RTI and resources provided to the PIC, this commitment seems to wither away.

Under the RTI, the Government has appointed a PIC to address complaints about denial, refusal/non-provision of requested information, or providing false/incomplete information. It was anticipated that this would reduce corruption and inefficiency in government and would promote good governance and respect for human rights. The PIC has the power to enforce its orders and penalise officials who do not comply with these orders.

According to the legislation, all government bodies are required to publish their functions and duties, information about their officials, relevant policies, laws and rules, and other necessary information proactively on the web.

The preamble of the RTI states that the purpose of the law is to provide the right of access to information transparently and effectively, with a few exceptions including the notes parts of government files, opinions or recommendations, and minutes of meetings. Other exceptions include financial institution customer account information, private confidential documents, records relating to defence and national security, and individual privacy. A major exception is that the Minister-in-charge can declare any record not subject to access by simply saying that disclosure is harmful to the public interest (Section 7(f)). Public interest has not been defined in this law.

In an interesting development, the Supreme Court of Pakistan (SCP) has provided the information a citizen has struggled to obtain for more than four years by invoking the RTI and Article 19-A of the Constitution[@cheemaFirstSC2023]. The citizen had asked for details of total sanctioned strength of staff members of the SCP, the positions lying vacant, number of contractual staff, the positions created from 2017 onward, strength of female staff, number of disabled persons employed by the court, transgenders inducted against various positions and a certified copy of the latest approved service rules of the SCP.

The Chief Justice of Pakistan ruled that the RTI did not explicitly apply to the Court, leaving the matter for Parliament to amend the law to bring the SCP under the purview of this law. However, Justice Athar Minallah, in an additional note, wrote that *prima facie* SCP had not been expressly excluded from the definition of "public bodies" mentioned in the law. However, the SCP ruled to provide the requested information under Article 19A of the Constitution.

To understand the position of the Pakistan Information Commission (PIC), a detailed meeting was held with its representative. During the discussion, the representative recommended submitting a formal request for a meeting, which was duly done. However, despite several follow-up attempts, no time was scheduled for a formal interview. This lack of response raises concerns about the PIC’s commitment to upholding the right to information and promoting transparency.

Mr. Aftab Alam[@iradaMuhammadAftab] (Mr. Alam), a lawyer by qualification and head of the Institute for Research, Advocacy, and Development[@iradaInstituteResearch] (IRADA), has been working on the issue of freedom of information for over 20 years. At the very outset, Mr. Alam stated that the introduction of Article 19A in the Constitution of Pakistan, 1973, as a fundamental right was a breakthrough. Explaining the struggle behind the RTI, he said that "the civil society found Senator Farhatullah Babar[@FarhatullahBabar] as champion of the right to information in the Senate of Pakistan", without his help, it would have been difficult to have this legislation.

Mr. Alam highlighted the most significant improvement in RTI compared to the previous law: the introduction of Section 5, which obligates the public bodies to proactively disclose all the stated information on the website of that public body[@PreventionElectronic2016]. While explaining the exceptions, he noted that many of the exceptions are carved out under the disguise of public record. Even the Minister-in-Charge has the power to exclude any public record, he added. According to him, the only justified exceptions should be limited to the privacy of individuals, national security, and public order; the rest of the information should be open. The longer the list of exceptions, the weaker the right to information. In this regard, he referred to Article 19 of the International Covenant on Civil and Political Rights[@InternationalCovenant1967] (ICCPR), adopted by the General Assembly of the United Nations on 19 December 1966.

Talking about the practices under this law, he said that the office of the PIC lacked necessary resources, and for quite some time, many civil society organisations, including IRADA, had been providing secretarial support to the PIC. He disclosed that many appeals/applications for information were being rejected by the current Commissioners on minor technical grounds, such as the absence of an affidavit regarding non-filing of such application before any other forum.

Mr. Alam spoke about IRADA's studies regarding the implementation of the law, especially Section 5[@iradaFullOpen2019]. During the research, he found out that website of Ministry of Finance had quite a lot of information (48.72% compliance) and the websites of the Ministry of Overseas Pakistanis contained least amount of information (15.38% compliance), whereas the Information Ministry, which was expected to lead by example, remained in the middle (33.77% compliance).

Though the RTI says that it has an overriding effect on all other laws, in practice, the Official Secrets Act 1923 is given more importance in government offices than the RTI. Mr. Alam said that IRADA conducted research in 2021 on the capacity of the public bodies and their familiarity with this law, practice, and procedures. The IRADA study found that the majority of staff at these public bodies were either not fully familiar with the law or had resource constraints. He also noted that during training sessions of civil servants, greater emphasis was placed on the Official Secrets Act 1923 than on the Right of Access to Information Act 2017. He added that the amendments made in the Official Secrets Act 1923 in the years 2023 made it more stringent, then diluting it[@alamSiegeLegislative].

It is also strange to learn that the public information officers in various public bodies are neither adequately trained nor sufficiently resourced. Even the attitude of the PIC in rejecting information requests based on technical reasons is not one would expect from a champion of the right to information. Similarly, the RTI prescribes timelines for responding to the information requests by the public bodies; these timelines are rarely met in practice. The PIC has to rule on an appeal within 60 days, but it has a huge backlog of pending appeals beyond 60 days.

The creation of a dedicated body (PIC) to regulate and enforce the right to information is a commendable step. But when it comes to providing this body the necessary resources to do its job, the government seems to be lagging behind its commitment to the fundamental right.

To improve the situation, Mr. Alam suggested that the "curriculum of the civil service training needed to be revamped to make it more service-oriented. There should be only two categories of information: (1) public information and (2) confidential information." All other exceptions should be done away with, he suggested. No public body, including superior courts, should be outside the ambit of this law, he added.

In conclusion, Pakistan recognizes the right to information as a fundamental right, has a law supporting that fundamental right, and a regulatory body to enforce that law, but is still a long way from optimal levels of accountability and transparency.

**Summary of research findings**

**Policy gaps**

There are quite a few policy gaps in Pakistan concerning data policies. One obvious gap is that different public and private entities collect a lot of data, ranging from personal to financial, to economic, to demographic, and to environmental data, but there is no comprehensive policy on the standardization of data or its structuring. Only a basic law, the Electronic Transactions Ordinance 2002, provides legal and functional equivalence to the electronic data and records to the physical data and records.

Another example of the policy gap: Pakistan was early in the region to start building a comprehensive database of its citizens in the 70's and digitalise that database in the early 2000s. But, thus far, it has failed to enact a Data Protection law to protect the privacy of individuals and stop the misuse of the database.

NADRA has the personal data of every citizen of Pakistan, and FBR has access to the data of all major points of sale in the country, combined with other data collected by the telecom and banking sectors. However, Pakistan could still not use it to increase its tax base. The tax-to-GDP ratio of Pakistan is a meagre 9%.

In the presence of a comprehensive database of NADRA, the collection of individual data by ECP through expensive field surveys is a waste of time and resources, especially when the voters have to show their CNIC issued by NADRA to cast their votes.

The RTI has provisions regarding proactive disclosure of certain information, but Pakistan is still far from adopting an "open-by-default" policy. Despite the proactive disclosures requirement, there is no open data or information available about registered entities like partnership firms, trusts, NGOs, and cooperative societies, and the beneficial owners of these entities.

Pakistan does not have a specific program on **FOSS**. It did encourage the use of open-source operating systems and Office software under the IT Policy and Action Plan 2000. Later, under the Digital Pakistan Policy, it took a step further to enhance skills and capabilities within the government to evaluate open source ICT products and services and encourage R&D of "Open Source" across the country through appropriate means.

There are no open standards currently mandated or preferred by the government. In the Digital Pakistan Policy, while discussing "IoT, FinTech, Artificial Intelligence & Robotics," there is a mention of "open standards efforts," but nothing tangible is in practice yet.

The government has multiple organisations tasked to digitize and automate government processes, but it is yet to develop a data sharing platform that, regardless of ownership, link data from all government agencies and promote integration and sharing of data among government entities, according to the "Pakistan National ICT Industry Development White Paper"[@moiitPakistanNational2022].

Under Section 32 of PECA, service providers are required to retain traffic data for a minimum period of one year, but investigation agencies cannot gain access to it without court warrants. Some say that the intelligence agencies have unfettered access to the telecom users' data, though such data cannot be used in legal proceedings. The requirement of warrants significantly reduces the ability of law enforcement agencies to swiftly investigate an ongoing crime. It may also be noted that the Budapest Convention on Cybercrime 2001[@councilofeuropeConventionCybercrime2001] does not require a warrant or production order for gaining access to the traffic data, as this does not have personally identifiable data.

It has been noted that the Ministry of Climate Change and Environmental Coordination has adopted quite a few policies, but most are not available on its website. Even those policies available do not contain adequate data (especially population data) to have meaningful implementation or to assess the success or failure of the Policy.

**Friction between policies**

The most significant friction found in this study is between the Right of Access to Information Act 2017 (RTI) and the Official Secrets Act 1923 (OSA). Though RTI states it has an overriding effect on all other laws, in practice, the OSA is given more importance in government offices. The government also made the OSA more stringent by introducing regressive amendments in the year 2023. Offences under the OSA range from the death penalty to fourteen years imprisonment; therefore, the government officials prefer to refuse access to information rather than facilitating it. In my view, this friction can easily be resolved by defining which category of documents can be labelled secret. The rest can be shared under the RTI, either by amending the OSA or by issuing binding instructions. In the absence of such clarity, everything is secret.

The draft PDP allows free flow of personal data with consent of the data subject, but sector regulators like SBP and PTA force their licensees to keep the personal data within Pakistan. The government is aware of this friction, but the PDP gives it no power to direct other sector regulators to allow the free flow of data. However, MoITT officials hope that things will change once the PDP is enacted. The PDP also does not prescribe a mechanism to address privacy concerns in other regulated sectors like telecom and banking. They also hope that after PDP, NADRA will stop selling data of citizens without their information or consent. In my view, leaving it to the sector regulators is not a good solution; the PDP must make it mandatory for the sector regulators to follow it in letter and spirit.

The draft National Artificial Intelligence Policy 2023 claims to be consistent with the Personal Data Protection Bill, Pakistan Cloud First Policy, and the Digital Pakistan Policy initiatives. However, there is a major conflict between this policy and the PDP Bill. The PDP Bill focuses primarily on protecting the privacy and personal data of individuals, whereas AI development depends on access to large amounts of data. Though it is a complex problem and not limited to Pakistan only but still PDP needs to make an exception for the promotion of AI in the country.

In the presence of RTI and right to information as a fundamental right, getting "sensitive data" (not sure what it means) of the Statistical Authority requires prior approval from the Federal Statistics Authority, which may or may not be granted. Similarly, the maps and data of the Survey of Pakistan can be obtained for a fee, but there are very stringent requirements on their use. This data cannot be shared with third parties or exported outside Pakistan. Commercial use is also prohibited. Even otherwise, it is strange to have such restrictions on maps in the era of Google Maps, which are much more detailed and free.

In a recent case, the SCP (details above) has ruled that the RTI didn't explicitly apply to the SCP, leaving the matter for the Parliament to amend the law in order to bring the SCP under this law, but it had to provide the requested information under Article 19A of the Constitution. Therefore, according to the SCP, this issue can be fixed by extending the RTI to the courts.

Interestingly, the National Archives Act makes an exception to disclosure if the record has any impact on national security. However, there is no such exception for the privacy of individuals in the Act. After the enactment of RTI, the privacy of individuals has to be protected at all costs, even if it requires an amendment to the National Archives Act.

**Policy objectives, trade-offs & their recognition**

In all spheres of governance – from economy, to governance style, to transparency – Pakistan has mixed priorities. The economy was initially based on private enterprise; in the 70s, nationalization happened; by the 80s, Islamization of the economy was the agenda, and in the 90s, the gears shifted to privatization. Currently, Pakistan operates as a mixed economy, in which state-owned enterprises compete with the private sector and play a major role in the economy. Similarly, in the realm of governance, it has tried three constitutions, four periods of martial law, presidential and parliamentary forms of government, and recently the hybrid regime, a term many use to explain martial law in the garb of a civilian government[@PunjabUndesirable1993].

Similarly, mixed priorities are visible when it comes to transparency in governance and open data. As noted elsewhere in this report, Pakistan's Constitution enshrines the right to information as a fundamental right, but the focus in 2023 seems to be strengthening the OSA, not improving the RTI. Pakistan was part of the Open Government Partnership[@OpenGovPartnershipPK] (OGP) and established an open data portal[@OpenDataPK], but on March 7, 2022, was removed from the OGP[@OGPPakistanLetter2022].

Both privacy and freedom of information are fundamental rights, associated with the highest level of sanctity. In practice, however, without a privacy or data protection law, there is no mechanism for the enjoyment of the right to privacy. For the right to information, there is a law, but the government does not seem to be interested in adequately resourcing or fully empowering the custodian of the law, the PIC.

**Good practices & potential learnings**

A strong signal of Pakistan's commitment to the right to information is the 2010 amendment inserting it as a fundamental right in the Constitution. The subsequent enactment of the RTI provides a mechanism for exercising that right, which is the right path towards a more transparent and open governance style.

Under the RTI, the introduction of Section 5 to enforce proactive disclosure is a very progressive step. Because of the Section, the majority of public bodies have made quite a lot of information available on their websites, including related laws, policies, and other useful information. The other good change was the creation of the PIC as a custodian of the right to information.

When it comes to proactive disclosure of information, the Finance Division of the Government of Pakistan has taken the lead over everyone else. It shares an annual budget and publishes monthly and annual economic surveys. The annual data shared on its website contains an overview of the economy, growth, and investment status, updates on all sectors, inflation, trade and payments, public debt, health and nutrition, population, labour force and employment, social protection, climate change, and economic and social indicators.

**Openness of policy development procedures**

When it comes to the openness of policy development, the MoITT has taken a leadership position. Since its creation in the year 2000, it has held open and meaningful public consultations on all of its policies and laws, starting from the IT Policy, 2000, to the draft PDP in 2023 and the draft National AI Policy.

According to the officials of the MoITT, PDP is the most consulted draft law in Pakistan. The broad-based consultation started in the year 2020, and three rounds of consultations were done. More than 100 companies and entities provided feedback, including local and international companies, and even the European Union submitted comments. Though digital rights activists still have reservations, it must be noted that the last draft was significantly different from the first draft, as the last one incorporated feedback from different stakeholders.

The wide consultation processes for over three years for the draft PDP demonstrate the maturity and confidence of the MoITT. They were open to criticism and ready to accept their mistakes and improve the draft legislation to make it acceptable to the majority of the stakeholders, if not all. This step needs to be recognised and appreciated, so that the government is further encouraged to do more meaningful consultations.

**Policy development capacity challenges**

The examples of PDP and RTI show that government capacity to develop good policies and laws does exist. The wider consultation processes also prove the flexibility of taking feedback and improving drafts. However, it seems that the real issue is not the capacity but the will to execute the policies or struggle through the mixed priorities, explained above.

The illusion of lack of capacity emerges amidst, on the one hand, the desire to attract much-needed investment, which needs increasing government accountability, and the urge to have stronger state control on the other.

In the laws, phrases like "critical personal data", "legitimate interest", "public interest", "national security", "secret", or "official secret", and "prejudicial to public order, defence, safety or interests of the State" reflect the desire to have control over desirable outcomes even when laws relating to privacy and right to information are enacted.

Climate change is another area where policymaking capacity does exist, but execution falters. Pakistan is one of the countries worst affected by, and at high risk of, climate change and related events. It has developed multiple policies to combat climate change, and the Pakistan Meteorological Department collects and maintains data about climate change and issues warnings. However, when it comes to risk mitigation, Pakistan's absence from the Climate Change Performance Index 2023 speaks volumes.

Despite what has been discussed above, Pakistan has no option but to move forward to generate more and more actionable data using digital technologies and disclose these datasets to the public for more democratic and inclusive governance.